// <auto-generated />
using System;
using Dimes.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dimes.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(DimesDbContext))]
    [Migration("20260623122038_AddChangeKeyAndNumber")]
    partial class AddChangeKeyAndNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dimes.Domain.Entities.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSiteAdmin")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LlmProviderConfigId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LlmProviderConfigId");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.AssistConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssistantActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChangeRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Draft")
                        .HasColumnType("text");

                    b.Property<Guid?>("ObservationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequesterActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssistantActorId");

                    b.HasIndex("ChangeRequestId");

                    b.HasIndex("ObservationId");

                    b.HasIndex("RequesterActorId");

                    b.HasIndex("ProjectId", "AssistantActorId", "Status");

                    b.ToTable("AssistConversations");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.AssistMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorActorId");

                    b.HasIndex("ConversationId");

                    b.ToTable("AssistMessages");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FromStatus")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToStatus")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.ChangeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssigneeActorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("DuplicateOfId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeActorId");

                    b.HasIndex("CreatedByActorId");

                    b.HasIndex("DuplicateOfId");

                    b.HasIndex("ProjectId", "Number")
                        .IsUnique();

                    b.HasIndex("ProjectId", "Status");

                    b.ToTable("ChangeRequests");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ChangeRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorActorId");

                    b.HasIndex("ChangeRequestId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.LlmProviderConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeySecretRef")
                        .HasColumnType("text");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("LlmProviderConfigs");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.LocalCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActorId")
                        .IsUnique();

                    b.ToTable("LocalCredentials");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ActorId", "ProjectId")
                        .IsUnique();

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChangeRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContextMetadata")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fingerprint")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("integer");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TargetActorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChangeRequestId");

                    b.HasIndex("SourceId");

                    b.HasIndex("TargetActorId");

                    b.HasIndex("ProjectId", "Fingerprint");

                    b.HasIndex("ProjectId", "Status");

                    b.HasIndex("ProjectId", "TargetActorId", "Status");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.ObservationSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SecretRef")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ObservationSources");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("HumanOnly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SourceControlEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.ScmLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChangeRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContextSnapshot")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChangeRequestId");

                    b.ToTable("ScmLinks");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.ScmProviderConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenSecretRef")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ScmProviderConfigs");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.Actor", b =>
                {
                    b.HasOne("Dimes.Domain.Entities.LlmProviderConfig", "LlmProviderConfig")
                        .WithMany()
                        .HasForeignKey("LlmProviderConfigId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LlmProviderConfig");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.AssistConversation", b =>
                {
                    b.HasOne("Dimes.Domain.Entities.Actor", "Assistant")
                        .WithMany()
                        .HasForeignKey("AssistantActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dimes.Domain.Entities.ChangeRequest", "ChangeRequest")
                        .WithMany()
                        .HasForeignKey("ChangeRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Dimes.Domain.Entities.Observation", "Observation")
                        .WithMany()
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Dimes.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dimes.Domain.Entities.Actor", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assistant");

                    b.Navigation("ChangeRequest");

                    b.Navigation("Observation");

                    b.Navigation("Project");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.AssistMessage", b =>
                {
                    b.HasOne("Dimes.Domain.Entities.Actor", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dimes.Domain.Entities.AssistConversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.AuditEvent", b =>
                {
                    b.HasOne("Dimes.Domain.Entities.Actor", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.ChangeRequest", b =>
                {
                    b.HasOne("Dimes.Domain.Entities.Actor", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeActorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dimes.Domain.Entities.Actor", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dimes.Domain.Entities.ChangeRequest", "DuplicateOf")
                        .WithMany()
                        .HasForeignKey("DuplicateOfId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dimes.Domain.Entities.Project", "Project")
                        .WithMany("ChangeRequests")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("CreatedBy");

                    b.Navigation("DuplicateOf");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Dimes.Domain.Entities.Actor", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dimes.Domain.Entities.ChangeRequest", "ChangeRequest")
                        .WithMany("Comments")
                        .HasForeignKey("ChangeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("ChangeRequest");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.LlmProviderConfig", b =>
                {
                    b.HasOne("Dimes.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.LocalCredential", b =>
                {
                    b.HasOne("Dimes.Domain.Entities.Actor", "Actor")
                        .WithOne()
                        .HasForeignKey("Dimes.Domain.Entities.LocalCredential", "ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.Membership", b =>
                {
                    b.HasOne("Dimes.Domain.Entities.Actor", "Actor")
                        .WithMany("Memberships")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dimes.Domain.Entities.Project", "Project")
                        .WithMany("Memberships")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.Observation", b =>
                {
                    b.HasOne("Dimes.Domain.Entities.ChangeRequest", "ChangeRequest")
                        .WithMany("Evidence")
                        .HasForeignKey("ChangeRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Dimes.Domain.Entities.Project", "Project")
                        .WithMany("Observations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dimes.Domain.Entities.ObservationSource", "Source")
                        .WithMany("Observations")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dimes.Domain.Entities.Actor", "TargetActor")
                        .WithMany()
                        .HasForeignKey("TargetActorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChangeRequest");

                    b.Navigation("Project");

                    b.Navigation("Source");

                    b.Navigation("TargetActor");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.ObservationSource", b =>
                {
                    b.HasOne("Dimes.Domain.Entities.Project", "Project")
                        .WithMany("ObservationSources")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.ScmLink", b =>
                {
                    b.HasOne("Dimes.Domain.Entities.ChangeRequest", "ChangeRequest")
                        .WithMany("ScmLinks")
                        .HasForeignKey("ChangeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangeRequest");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.ScmProviderConfig", b =>
                {
                    b.HasOne("Dimes.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.Actor", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.AssistConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.ChangeRequest", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Evidence");

                    b.Navigation("ScmLinks");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.ObservationSource", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("Dimes.Domain.Entities.Project", b =>
                {
                    b.Navigation("ChangeRequests");

                    b.Navigation("Memberships");

                    b.Navigation("ObservationSources");

                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
